server:
  port: 8080

spring:
  application:
    name: restful-service

logging:
  level:
    org.springframework: DEBUG

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"