server:
  port: 8080

spring:
  application:
    name: restful-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

logging:
  level:
    org.springframework: DEBUG

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"