server:
  port: 9000
  # Auto port

spring:
  application:
    name: user-service
    # DB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mydb.cvttgezbigrm.ap-northeast-2.rds.amazonaws.com

    username: admin
    password: 43214321

# mybatis.type-aliases-package= DTO Path
#
#  SQL Query Location
# mybatis.mapper-locations=classpath: mapper Path
#
#  JSP Location
# spring.mvc.view.prefix=/WEB-INF/views/
# spring.mvc.view.suffix=.jsp

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      DefaultZone: http://localhost:8761/eureka